# yaml 配置实例
version: '3'
services:
  web:
    image: docker-demo/hello-docker:v3
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
    ports:
      - "8080:8080"
  redis:
    image: redis:alpine