version: "3"

networks: # 自定义网络
  my-network: # 网络名字
    driver: bridge # 由网关驱动

volumes: # 创建自定义卷
  node_modules: # 卷名
  mongo_data:

services: # 定义每个容器的服务

### nginx ###
  nginx:
    build: 
      context: ./nginx
    ports: 
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/cert:/etc/nginx/cret
      - ./logs/nginx:/var/log/nginx
    restart: always #服务挂了时自动重启
    depends_on: # 定义容器的启动顺序，附带容器间的依赖关系
      - nodejs
    networks: # 使用我们上面定义的网络
      - my-network
  
### node ###
  nodejs:
    build:
      context: ./node # 构建 node 目录，会去 node 下面找 Dockerfile
    ports:
      - 127.0.0.1:7001:7001
    volumes:
      - ./node:/app/
      - node_modules:/app/node_modules
    restart: always # 服务挂了时自动重启
    depends_on: 
      - mongo
    networks:
      - my-network

### mongoDB ###
  mongo:
    build:
      context: ./mongo
    ports:
      - 127.0.0.1:27018:27018
    volumes:
      - mongo_data:/data/db
    restart: always # 服务挂了时自动重启
    networks:
      - my-network
      